// ============================================================
// Seed Script — 50+ Realistic Internship Listings
// Run: npm run seed (or node utils/seed.js)
// ============================================================
require('dotenv').config({ path: require('path').join(__dirname, '..', '.env') });
const mongoose = require('mongoose');
const Internship = require('../models/Internship');
const connectDB = require('./db');

const internships = [
  // ===== SOFTWARE ENGINEERING =====
  {
    title: 'Frontend Developer Intern',
    company: 'Flipkart',
    location: 'Bangalore',
    type: 'hybrid',
    skills_required: ['React', 'JavaScript', 'CSS', 'HTML', 'TypeScript'],
    stipend: '₹25,000/month',
    description: 'Join Flipkart\'s frontend team to build high-performance e-commerce UIs using React and TypeScript. Work on product detail pages and checkout flow used by millions daily.',
    link: 'https://www.flipkart.com/careers',
    source: 'Company Website',
    duration: '6 months',
    deadline: new Date('2026-05-15'),
  },
  {
    title: 'Backend Engineering Intern',
    company: 'Razorpay',
    location: 'Bangalore',
    type: 'onsite',
    skills_required: ['Node.js', 'Python', 'MongoDB', 'REST API', 'Docker'],
    stipend: '₹40,000/month',
    description: 'Work on Razorpay\'s payment processing backend, handling millions of transactions. Build and optimize APIs with microservices architecture.',
    link: 'https://razorpay.com/jobs/',
    source: 'Company Website',
    duration: '6 months',
    deadline: new Date('2026-04-30'),
  },
  {
    title: 'Full Stack Developer Intern',
    company: 'Zomato',
    location: 'Gurugram',
    type: 'onsite',
    skills_required: ['React', 'Node.js', 'MongoDB', 'Express', 'Git'],
    stipend: '₹30,000/month',
    description: 'Build features for Zomato\'s restaurant discovery platform across the entire stack from React frontend to Node.js APIs.',
    link: 'https://www.zomato.com/careers',
    source: 'Company Website',
    duration: '3 months',
    deadline: new Date('2026-05-01'),
  },
  {
    title: 'Software Development Intern',
    company: 'Google',
    location: 'Hyderabad',
    type: 'onsite',
    skills_required: ['Python', 'C++', 'Data Structures', 'Algorithms', 'System Design'],
    stipend: '₹80,000/month',
    description: 'Join Google\'s engineering team to work on products impacting billions. Solve complex algorithmic problems and contribute to distributed systems.',
    link: 'https://careers.google.com/students/',
    source: 'LinkedIn',
    duration: '3 months',
    deadline: new Date('2026-04-15'),
  },
  {
    title: 'Mobile App Developer Intern',
    company: 'Paytm',
    location: 'Noida',
    type: 'onsite',
    skills_required: ['React Native', 'JavaScript', 'Firebase', 'REST API', 'Redux'],
    stipend: '₹20,000/month',
    description: 'Build and enhance Paytm\'s mobile applications used by 300M+ users. Integrate payment SDKs and optimize app performance.',
    link: 'https://paytm.com/careers',
    source: 'Internshala',
    duration: '4 months',
    deadline: new Date('2026-05-20'),
  },
  {
    title: 'Python Developer Intern',
    company: 'Infosys',
    location: 'Pune',
    type: 'hybrid',
    skills_required: ['Python', 'Django', 'PostgreSQL', 'REST API', 'Git'],
    stipend: '₹15,000/month',
    description: 'Develop enterprise web applications using Python and Django. Build RESTful APIs and implement authentication systems.',
    link: 'https://www.infosys.com/careers/internship.html',
    source: 'Internshala',
    duration: '3 months',
    deadline: new Date('2026-06-01'),
  },
  {
    title: 'DevOps Engineering Intern',
    company: 'PhonePe',
    location: 'Bangalore',
    type: 'onsite',
    skills_required: ['Docker', 'Kubernetes', 'AWS', 'Linux', 'CI/CD', 'Shell Scripting'],
    stipend: '₹35,000/month',
    description: 'Join PhonePe\'s infrastructure team. Automate deployment pipelines, manage Kubernetes clusters, and ensure platform reliability.',
    link: 'https://www.phonepe.com/careers/',
    source: 'LinkedIn',
    duration: '6 months',
    deadline: new Date('2026-04-25'),
  },
  {
    title: 'Java Developer Intern',
    company: 'Walmart Global Tech',
    location: 'Bangalore',
    type: 'hybrid',
    skills_required: ['Java', 'Spring Boot', 'Microservices', 'SQL', 'REST API'],
    stipend: '₹45,000/month',
    description: 'Build scalable microservices for Walmart\'s e-commerce platform serving millions of customers. Work with Spring Boot and cloud-native technologies.',
    link: 'https://careers.walmart.com/',
    source: 'LinkedIn',
    duration: '6 months',
    deadline: new Date('2026-05-12'),
  },
  {
    title: 'Software Engineer Intern',
    company: 'Adobe',
    location: 'Noida',
    type: 'onsite',
    skills_required: ['C++', 'JavaScript', 'React', 'Data Structures', 'Algorithms'],
    stipend: '₹50,000/month',
    description: 'Work on Adobe\'s creative tools used by millions of designers worldwide. Build performance-critical features in C++ and modern web UIs in React.',
    link: 'https://www.adobe.com/careers.html',
    source: 'Company Website',
    duration: '3 months',
    deadline: new Date('2026-04-28'),
  },
  {
    title: 'Backend Developer Intern',
    company: 'Ola',
    location: 'Bangalore',
    type: 'onsite',
    skills_required: ['Go', 'Python', 'Kafka', 'Redis', 'Microservices'],
    stipend: '₹30,000/month',
    description: 'Build backend systems powering Ola\'s ride-hailing platform. Work with Go, event-driven architecture, and real-time data processing.',
    link: 'https://www.olacabs.com/careers',
    source: 'LinkedIn',
    duration: '4 months',
    deadline: new Date('2026-05-18'),
  },
  {
    title: 'MERN Stack Developer Intern',
    company: 'Coding Ninjas',
    location: 'Remote',
    type: 'remote',
    skills_required: ['MongoDB', 'Express', 'React', 'Node.js', 'JavaScript'],
    stipend: '₹15,000/month',
    description: 'Build full-stack web applications and contribute to the Coding Ninjas learning platform. Great opportunity for hands-on MERN experience.',
    link: 'https://www.codingninjas.com/careers',
    source: 'Internshala',
    duration: '3 months',
    deadline: new Date('2026-06-10'),
  },
  {
    title: 'SDE Intern',
    company: 'Amazon',
    location: 'Hyderabad',
    type: 'onsite',
    skills_required: ['Java', 'Python', 'AWS', 'Data Structures', 'System Design'],
    stipend: '₹60,000/month',
    description: 'Work on Amazon\'s core services powering the world\'s largest marketplace. Design and implement scalable solutions using AWS infrastructure.',
    link: 'https://www.amazon.jobs/en/teams/internships-for-students',
    source: 'LinkedIn',
    duration: '3 months',
    deadline: new Date('2026-04-20'),
  },
  {
    title: 'React Developer Intern',
    company: 'Swiggy',
    location: 'Bangalore',
    type: 'hybrid',
    skills_required: ['React', 'TypeScript', 'Redux', 'CSS', 'Jest'],
    stipend: '₹28,000/month',
    description: 'Build UI components for Swiggy\'s food delivery app. Work with React, TypeScript, and modern state management patterns.',
    link: 'https://careers.swiggy.com/',
    source: 'Company Website',
    duration: '4 months',
    deadline: new Date('2026-05-22'),
  },
  {
    title: 'API Developer Intern',
    company: 'Postman',
    location: 'Bangalore',
    type: 'hybrid',
    skills_required: ['Node.js', 'REST API', 'GraphQL', 'TypeScript', 'Testing'],
    stipend: '₹35,000/month',
    description: 'Help build the world\'s most popular API development platform. Design RESTful and GraphQL APIs, write comprehensive tests.',
    link: 'https://www.postman.com/company/careers/',
    source: 'Company Website',
    duration: '6 months',
    deadline: new Date('2026-05-08'),
  },

  // ===== DATA SCIENCE & AI/ML =====
  {
    title: 'Data Science Intern',
    company: 'Swiggy',
    location: 'Bangalore',
    type: 'hybrid',
    skills_required: ['Python', 'Machine Learning', 'Pandas', 'SQL', 'TensorFlow'],
    stipend: '₹35,000/month',
    description: 'Apply ML models to optimize delivery logistics, build recommendation engines, and analyze customer behavior patterns.',
    link: 'https://careers.swiggy.com/',
    source: 'LinkedIn',
    duration: '6 months',
    deadline: new Date('2026-05-10'),
  },
  {
    title: 'Machine Learning Intern',
    company: 'Microsoft',
    location: 'Hyderabad',
    type: 'onsite',
    skills_required: ['Python', 'PyTorch', 'Deep Learning', 'NLP', 'Computer Vision'],
    stipend: '₹60,000/month',
    description: 'Research and develop ML models for Microsoft products. Work on NLP, computer vision, and generative AI with world-class researchers.',
    link: 'https://careers.microsoft.com/students/',
    source: 'Company Website',
    duration: '3 months',
    deadline: new Date('2026-04-20'),
  },
  {
    title: 'AI Research Intern',
    company: 'Samsung R&D',
    location: 'Bangalore',
    type: 'onsite',
    skills_required: ['Python', 'Deep Learning', 'Computer Vision', 'TensorFlow', 'OpenCV'],
    stipend: '₹30,000/month',
    description: 'Work on AI-powered camera features for Samsung Galaxy devices. Build and train deep learning models for real-time image processing.',
    link: 'https://research.samsung.com/careers',
    source: 'LinkedIn',
    duration: '6 months',
    deadline: new Date('2026-05-30'),
  },
  {
    title: 'Data Analyst Intern',
    company: 'Dream11',
    location: 'Mumbai',
    type: 'hybrid',
    skills_required: ['SQL', 'Python', 'Excel', 'Tableau', 'Data Analysis'],
    stipend: '₹25,000/month',
    description: 'Analyze user engagement data for India\'s largest fantasy sports platform. Build dashboards and drive product decisions with data.',
    link: 'https://www.dreamsports.group/careers',
    source: 'Internshala',
    duration: '3 months',
    deadline: new Date('2026-05-15'),
  },
  {
    title: 'NLP Engineer Intern',
    company: 'Flipkart',
    location: 'Bangalore',
    type: 'onsite',
    skills_required: ['Python', 'NLP', 'TensorFlow', 'BERT', 'Deep Learning'],
    stipend: '₹35,000/month',
    description: 'Build NLP models for search and product recommendations. Work with transformer models and improve search relevance.',
    link: 'https://www.flipkart.com/careers',
    source: 'Company Website',
    duration: '6 months',
    deadline: new Date('2026-04-30'),
  },
  {
    title: 'Computer Vision Intern',
    company: 'Intel',
    location: 'Hyderabad',
    type: 'onsite',
    skills_required: ['Python', 'OpenCV', 'Deep Learning', 'PyTorch', 'C++'],
    stipend: '₹40,000/month',
    description: 'Develop computer vision algorithms for Intel\'s edge computing products. Optimize deep learning models for real-time inference on Intel hardware.',
    link: 'https://www.intel.com/content/www/us/en/jobs/student.html',
    source: 'LinkedIn',
    duration: '6 months',
    deadline: new Date('2026-05-05'),
  },
  {
    title: 'Generative AI Intern',
    company: 'Infosys',
    location: 'Remote',
    type: 'remote',
    skills_required: ['Python', 'LLM', 'Prompt Engineering', 'LangChain', 'OpenAI API'],
    stipend: '₹20,000/month',
    description: 'Build enterprise AI applications using large language models. Work with LangChain, prompt engineering, and RAG architectures.',
    link: 'https://www.infosys.com/careers/internship.html',
    source: 'Internshala',
    duration: '3 months',
    deadline: new Date('2026-06-15'),
  },

  // ===== DESIGN =====
  {
    title: 'UI/UX Design Intern',
    company: 'CRED',
    location: 'Bangalore',
    type: 'onsite',
    skills_required: ['Figma', 'Adobe XD', 'UI/UX', 'Prototyping', 'Design Systems'],
    stipend: '₹30,000/month',
    description: 'Design beautiful, intuitive interfaces for CRED\'s award-winning fintech app. Create wireframes, prototypes, and design systems.',
    link: 'https://cred.club/careers',
    source: 'Company Website',
    duration: '4 months',
    deadline: new Date('2026-05-05'),
  },
  {
    title: 'Product Design Intern',
    company: 'Notion',
    location: 'Remote',
    type: 'remote',
    skills_required: ['Figma', 'UI/UX', 'User Research', 'Prototyping', 'Design Thinking'],
    stipend: '₹45,000/month',
    description: 'Shape the future of productivity tools. Conduct user research, create design systems, and prototype new features.',
    link: 'https://www.notion.so/careers',
    source: 'LinkedIn',
    duration: '3 months',
    deadline: new Date('2026-04-28'),
  },
  {
    title: 'Graphic Design Intern',
    company: 'Canva',
    location: 'Remote',
    type: 'remote',
    skills_required: ['Photoshop', 'Illustrator', 'Figma', 'Typography', 'Brand Design'],
    stipend: '₹20,000/month',
    description: 'Create visual assets and design templates for Canva\'s marketplace. Work with the brand team on marketing materials.',
    link: 'https://www.canva.com/careers/',
    source: 'Internshala',
    duration: '3 months',
    deadline: new Date('2026-06-10'),
  },
  {
    title: 'Motion Graphics Intern',
    company: 'Unacademy',
    location: 'Bangalore',
    type: 'hybrid',
    skills_required: ['After Effects', 'Premiere Pro', 'Motion Graphics', 'Figma', 'Animation'],
    stipend: '₹18,000/month',
    description: 'Create engaging educational animations and motion graphics for Unacademy\'s learning platform and marketing campaigns.',
    link: 'https://unacademy.com/careers',
    source: 'Internshala',
    duration: '3 months',
    deadline: new Date('2026-05-25'),
  },

  // ===== MARKETING & CONTENT =====
  {
    title: 'Digital Marketing Intern',
    company: 'Zerodha',
    location: 'Bangalore',
    type: 'hybrid',
    skills_required: ['SEO', 'Google Analytics', 'Content Writing', 'Social Media', 'Digital Marketing'],
    stipend: '₹15,000/month',
    description: 'Drive growth for India\'s largest stock broker. Manage SEO campaigns, create financial content, and analyze marketing funnels.',
    link: 'https://zerodha.com/careers/',
    source: 'Internshala',
    duration: '3 months',
    deadline: new Date('2026-05-25'),
  },
  {
    title: 'Content Marketing Intern',
    company: 'Razorpay',
    location: 'Remote',
    type: 'remote',
    skills_required: ['Content Writing', 'SEO', 'Social Media', 'Copywriting', 'Research'],
    stipend: '₹12,000/month',
    description: 'Create engaging fintech content for Razorpay\'s blog and social channels. Write SEO-optimized articles and manage content calendars.',
    link: 'https://razorpay.com/jobs/',
    source: 'Internshala',
    duration: '2 months',
    deadline: new Date('2026-06-15'),
  },
  {
    title: 'Social Media Intern',
    company: 'boAt',
    location: 'Delhi',
    type: 'onsite',
    skills_required: ['Social Media', 'Content Writing', 'Canva', 'Video Editing', 'Marketing'],
    stipend: '₹12,000/month',
    description: 'Manage boAt\'s social media across Instagram, Twitter and YouTube. Create viral content and track metrics.',
    link: 'https://www.boat-lifestyle.com/pages/careers',
    source: 'Internshala',
    duration: '3 months',
    deadline: new Date('2026-05-18'),
  },
  {
    title: 'Growth Marketing Intern',
    company: 'Groww',
    location: 'Bangalore',
    type: 'hybrid',
    skills_required: ['Marketing', 'Data Analysis', 'Google Analytics', 'A/B Testing', 'SQL'],
    stipend: '₹22,000/month',
    description: 'Drive user acquisition and retention for India\'s fastest-growing investment platform. Run experiments, optimize funnels, and analyze growth metrics.',
    link: 'https://groww.in/careers',
    source: 'LinkedIn',
    duration: '4 months',
    deadline: new Date('2026-05-10'),
  },

  // ===== CYBERSECURITY =====
  {
    title: 'Cybersecurity Intern',
    company: 'Tata Consultancy Services',
    location: 'Mumbai',
    type: 'onsite',
    skills_required: ['Cybersecurity', 'Linux', 'Networking', 'Python', 'Ethical Hacking'],
    stipend: '₹20,000/month',
    description: 'Join TCS\'s security operations center. Perform vulnerability assessments and strengthen enterprise security posture.',
    link: 'https://www.tcs.com/careers',
    source: 'Company Website',
    duration: '6 months',
    deadline: new Date('2026-05-10'),
  },
  {
    title: 'Security Analyst Intern',
    company: 'Wipro',
    location: 'Hyderabad',
    type: 'onsite',
    skills_required: ['SIEM', 'Network Security', 'Linux', 'Python', 'Incident Response'],
    stipend: '₹18,000/month',
    description: 'Monitor security events, investigate alerts, and support incident response activities in Wipro\'s cybersecurity practice.',
    link: 'https://careers.wipro.com/',
    source: 'Company Website',
    duration: '6 months',
    deadline: new Date('2026-05-20'),
  },

  // ===== CLOUD & DEVOPS =====
  {
    title: 'Cloud Engineering Intern',
    company: 'Amazon Web Services',
    location: 'Hyderabad',
    type: 'onsite',
    skills_required: ['AWS', 'Python', 'Docker', 'Terraform', 'Linux'],
    stipend: '₹50,000/month',
    description: 'Work with AWS cloud services at scale. Build infrastructure automation and help enterprises migrate to the cloud.',
    link: 'https://www.amazon.jobs/en/teams/internships-for-students',
    source: 'LinkedIn',
    duration: '3 months',
    deadline: new Date('2026-04-18'),
  },
  {
    title: 'Site Reliability Engineering Intern',
    company: 'Atlassian',
    location: 'Bangalore',
    type: 'hybrid',
    skills_required: ['Python', 'Kubernetes', 'AWS', 'Monitoring', 'Linux'],
    stipend: '₹45,000/month',
    description: 'Ensure reliability and performance of Atlassian\'s cloud products. Build monitoring, alerting, and automation tools for production systems.',
    link: 'https://www.atlassian.com/company/careers',
    source: 'LinkedIn',
    duration: '6 months',
    deadline: new Date('2026-05-08'),
  },

  // ===== BLOCKCHAIN & WEB3 =====
  {
    title: 'Blockchain Developer Intern',
    company: 'Polygon',
    location: 'Remote',
    type: 'remote',
    skills_required: ['Solidity', 'Ethereum', 'Web3', 'JavaScript', 'Blockchain'],
    stipend: '₹40,000/month',
    description: 'Build decentralized apps on Polygon\'s L2 network. Write smart contracts and contribute to open-source blockchain tooling.',
    link: 'https://polygon.technology/careers',
    source: 'LinkedIn',
    duration: '4 months',
    deadline: new Date('2026-05-20'),
  },
  {
    title: 'Web3 Frontend Intern',
    company: 'CoinDCX',
    location: 'Mumbai',
    type: 'hybrid',
    skills_required: ['React', 'Web3.js', 'TypeScript', 'Ethers.js', 'MetaMask'],
    stipend: '₹25,000/month',
    description: 'Build Web3 frontend interfaces for CoinDCX\'s crypto exchange. Integrate wallet connections, display real-time market data.',
    link: 'https://coindcx.com/careers',
    source: 'LinkedIn',
    duration: '3 months',
    deadline: new Date('2026-05-15'),
  },

  // ===== MOBILE DEVELOPMENT =====
  {
    title: 'Android Developer Intern',
    company: 'ShareChat',
    location: 'Bangalore',
    type: 'onsite',
    skills_required: ['Kotlin', 'Android', 'Java', 'Firebase', 'REST API'],
    stipend: '₹25,000/month',
    description: 'Build features for ShareChat\'s social media app with 180M+ monthly users. Work with Kotlin and optimize app performance.',
    link: 'https://sharechat.com/careers',
    source: 'LinkedIn',
    duration: '3 months',
    deadline: new Date('2026-05-12'),
  },
  {
    title: 'iOS Developer Intern',
    company: 'Meesho',
    location: 'Bangalore',
    type: 'hybrid',
    skills_required: ['Swift', 'iOS', 'Xcode', 'UIKit', 'SwiftUI'],
    stipend: '₹30,000/month',
    description: 'Develop Meesho\'s iOS app used by millions of small businesses. Implement features with Swift and optimize user experience.',
    link: 'https://meesho.io/careers',
    source: 'Company Website',
    duration: '4 months',
    deadline: new Date('2026-05-08'),
  },
  {
    title: 'Flutter Developer Intern',
    company: 'Dunzo',
    location: 'Bangalore',
    type: 'onsite',
    skills_required: ['Flutter', 'Dart', 'Firebase', 'REST API', 'Git'],
    stipend: '₹20,000/month',
    description: 'Build cross-platform features for Dunzo\'s hyperlocal delivery app with Flutter. Integrate payment gateways and optimize app startup.',
    link: 'https://www.dunzo.com/careers',
    source: 'Internshala',
    duration: '3 months',
    deadline: new Date('2026-05-30'),
  },

  // ===== TESTING & QA =====
  {
    title: 'QA Automation Intern',
    company: 'Freshworks',
    location: 'Chennai',
    type: 'onsite',
    skills_required: ['Selenium', 'Python', 'Cypress', 'Jest', 'Testing'],
    stipend: '₹18,000/month',
    description: 'Ensure quality across Freshworks\' SaaS products. Write automated tests, perform regression testing, and improve test coverage.',
    link: 'https://www.freshworks.com/company/careers/',
    source: 'Internshala',
    duration: '3 months',
    deadline: new Date('2026-06-01'),
  },
  {
    title: 'SDET Intern',
    company: 'Intuit',
    location: 'Bangalore',
    type: 'hybrid',
    skills_required: ['Java', 'Selenium', 'API Testing', 'CI/CD', 'Postman'],
    stipend: '₹35,000/month',
    description: 'Design and implement test automation frameworks for Intuit\'s financial products. Write API tests, UI tests, and performance tests.',
    link: 'https://www.intuit.com/careers/',
    source: 'LinkedIn',
    duration: '6 months',
    deadline: new Date('2026-05-10'),
  },

  // ===== DATA ENGINEERING =====
  {
    title: 'Data Engineering Intern',
    company: 'Uber',
    location: 'Hyderabad',
    type: 'onsite',
    skills_required: ['Python', 'SQL', 'Apache Spark', 'Kafka', 'Data Engineering'],
    stipend: '₹55,000/month',
    description: 'Build data pipelines processing petabytes of ride data. Work with Spark, Kafka, and Hive for real-time analytics.',
    link: 'https://www.uber.com/us/en/careers/',
    source: 'LinkedIn',
    duration: '3 months',
    deadline: new Date('2026-04-22'),
  },
  {
    title: 'ETL Developer Intern',
    company: 'Mu Sigma',
    location: 'Bangalore',
    type: 'onsite',
    skills_required: ['SQL', 'Python', 'ETL', 'Airflow', 'Data Warehousing'],
    stipend: '₹20,000/month',
    description: 'Design and implement ETL pipelines for enterprise analytics clients. Work with Apache Airflow and cloud data warehouses.',
    link: 'https://www.mu-sigma.com/careers',
    source: 'Company Website',
    duration: '6 months',
    deadline: new Date('2026-05-28'),
  },

  // ===== BUSINESS & CONSULTING =====
  {
    title: 'Business Analyst Intern',
    company: 'Deloitte',
    location: 'Gurugram',
    type: 'onsite',
    skills_required: ['Excel', 'SQL', 'Power BI', 'Business Analysis', 'Presentation'],
    stipend: '₹20,000/month',
    description: 'Support consulting engagements with data-driven insights. Create dashboards, perform market research, and present to stakeholders.',
    link: 'https://www2.deloitte.com/careers',
    source: 'LinkedIn',
    duration: '3 months',
    deadline: new Date('2026-05-15'),
  },
  {
    title: 'Product Management Intern',
    company: 'Groww',
    location: 'Bangalore',
    type: 'hybrid',
    skills_required: ['Product Management', 'Data Analysis', 'SQL', 'Figma', 'Agile'],
    stipend: '₹28,000/month',
    description: 'Drive product strategy for Groww\'s investment platform. Conduct user research, define requirements, and analyze adoption metrics.',
    link: 'https://groww.in/careers',
    source: 'Internshala',
    duration: '3 months',
    deadline: new Date('2026-05-22'),
  },
  {
    title: 'Management Consulting Intern',
    company: 'McKinsey & Company',
    location: 'Mumbai',
    type: 'onsite',
    skills_required: ['Business Analysis', 'Excel', 'PowerPoint', 'Problem Solving', 'Research'],
    stipend: '₹75,000/month',
    description: 'Work on strategic consulting projects for Fortune 500 clients. Analyze business challenges, develop recommendations, and present solutions.',
    link: 'https://www.mckinsey.com/careers',
    source: 'Company Website',
    duration: '2 months',
    deadline: new Date('2026-04-30'),
  },

  // ===== GAME & CREATIVE =====
  {
    title: 'Game Developer Intern',
    company: 'Games24x7',
    location: 'Mumbai',
    type: 'onsite',
    skills_required: ['Unity', 'C#', 'Game Development', '3D Modeling', 'Physics Engine'],
    stipend: '₹22,000/month',
    description: 'Develop gaming experiences with Unity. Implement game mechanics, create visual effects, and optimize for mobile platforms.',
    link: 'https://www.games24x7.com/careers',
    source: 'Company Website',
    duration: '3 months',
    deadline: new Date('2026-05-28'),
  },

  // ===== TECHNICAL WRITING =====
  {
    title: 'Technical Writer Intern',
    company: 'Atlassian',
    location: 'Remote',
    type: 'remote',
    skills_required: ['Technical Writing', 'Documentation', 'Markdown', 'API Documentation', 'Git'],
    stipend: '₹25,000/month',
    description: 'Write developer documentation for Jira and Confluence. Create API guides, tutorials, and improve documentation clarity.',
    link: 'https://www.atlassian.com/company/careers',
    source: 'LinkedIn',
    duration: '3 months',
    deadline: new Date('2026-06-05'),
  },

  // ===== HARDWARE / EMBEDDED =====
  {
    title: 'Embedded Systems Intern',
    company: 'Qualcomm',
    location: 'Hyderabad',
    type: 'onsite',
    skills_required: ['C', 'C++', 'Embedded Systems', 'RTOS', 'ARM'],
    stipend: '₹45,000/month',
    description: 'Develop firmware for Qualcomm chipsets. Work with embedded C, RTOS, and ARM architecture for communication drivers.',
    link: 'https://www.qualcomm.com/company/careers',
    source: 'Company Website',
    duration: '6 months',
    deadline: new Date('2026-04-25'),
  },
  {
    title: 'IoT Developer Intern',
    company: 'Bosch',
    location: 'Bangalore',
    type: 'onsite',
    skills_required: ['C', 'Python', 'MQTT', 'IoT', 'Embedded Systems'],
    stipend: '₹25,000/month',
    description: 'Build IoT solutions for Bosch\'s smart home and automotive products. Work on sensor data processing and cloud connectivity.',
    link: 'https://www.bosch.in/careers/',
    source: 'Company Website',
    duration: '6 months',
    deadline: new Date('2026-05-15'),
  },

  // ===== FINANCE & FINTECH =====
  {
    title: 'Fintech Developer Intern',
    company: 'Cred',
    location: 'Bangalore',
    type: 'hybrid',
    skills_required: ['Java', 'Spring Boot', 'Kafka', 'PostgreSQL', 'Microservices'],
    stipend: '₹35,000/month',
    description: 'Build backend services for CRED\'s credit card payments platform. Work on transaction processing, rewards systems, and financial data.',
    link: 'https://cred.club/careers',
    source: 'LinkedIn',
    duration: '4 months',
    deadline: new Date('2026-05-12'),
  },
  {
    title: 'Quantitative Analysis Intern',
    company: 'Goldman Sachs',
    location: 'Bangalore',
    type: 'onsite',
    skills_required: ['Python', 'Statistics', 'Machine Learning', 'SQL', 'Financial Modeling'],
    stipend: '₹70,000/month',
    description: 'Apply quantitative methods to financial markets. Build pricing models, analyze risk, and develop trading algorithms.',
    link: 'https://www.goldmansachs.com/careers/',
    source: 'Company Website',
    duration: '3 months',
    deadline: new Date('2026-04-20'),
  },

  // ===== HR & OPERATIONS =====
  {
    title: 'HR Operations Intern',
    company: 'Deloitte',
    location: 'Mumbai',
    type: 'hybrid',
    skills_required: ['Excel', 'Communication', 'HRIS', 'Data Entry', 'Presentation'],
    stipend: '₹15,000/month',
    description: 'Support HR processes including recruitment, onboarding, and employee engagement. Gain exposure to consulting HR practices.',
    link: 'https://www2.deloitte.com/careers',
    source: 'Internshala',
    duration: '3 months',
    deadline: new Date('2026-06-01'),
  },
  {
    title: 'Supply Chain Intern',
    company: 'Flipkart',
    location: 'Bangalore',
    type: 'onsite',
    skills_required: ['Excel', 'Data Analysis', 'SQL', 'Supply Chain', 'Logistics'],
    stipend: '₹22,000/month',
    description: 'Optimize Flipkart\'s supply chain operations. Analyze logistics data, improve warehouse efficiency, and reduce delivery times.',
    link: 'https://www.flipkart.com/careers',
    source: 'Company Website',
    duration: '3 months',
    deadline: new Date('2026-05-20'),
  },
];

async function seedDB() {
  try {
    await connectDB();
    console.log('🗑️  Clearing existing internships...');
    await Internship.deleteMany({});
    
    console.log('🌱 Seeding internships...');
    await Internship.insertMany(internships);
    
    console.log(`✅ Successfully seeded ${internships.length} internships!`);
    process.exit(0);
  } catch (error) {
    console.error('❌ Seed error:', error.message);
    process.exit(1);
  }
}

seedDB();
